apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: git@github.com:cezarbajenaru/ekscourse_gitops_platform.git
    targetRevision: main
    path: apps/podinfo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/wordpress
    targetRevision: 28.0.2
    helm:
      releaseName: wordpress
      values: |
        service:
          type: ClusterIP
        ingress:
          enabled: false
        mariadb:
          enabled: true
          auth:
            rootPassword: "dev-root-password"
            password: "dev-wp-password"
            username: "bn_wordpress"
            database: "bitnami_wordpress"
          primary:
            persistence:
              enabled: true
              size: 8Gi
        persistence:
          enabled: true
          size: 10Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:cezarbajenaru/ekscourse_gitops_platform.git
    targetRevision: main
    path: argo/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true