apiVersion: v1
kind: Secret
metadata:
  name: git-cezarbajenaru-ekscourse
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:cezarbajenaru/ekscourse_gitops_platform.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCU4nYyU++QpBbrxIjn/GHLMU67QKaTWf/lOXqEUut91QAAAJi0vHcGtLx3
    BgAAAAtzc2gtZWQyNTUxOQAAACCU4nYyU++QpBbrxIjn/GHLMU67QKaTWf/lOXqEUut91Q
    AAAECN1JnPsNagYro0PMsF6nX/T13dz5Fb9sZEtRuDQ4HDJpTidjJT75CkFuvEiOf8Ycsx
    TrtAppNZ/+U5eoRS633VAAAAD2FyZ29jZEBtaW5pa3ViZQECAwQFBg==
    -----END OPENSSH PRIVATE KEY-----
